/**
 * One-time maintenance: normalize legacy "REP-XXXXXXXX" sales-rep codes
 * (auto-generated by an earlier version of linkUserAsSalesRep) to the short
 * uppercase convention, derived from each rep's name via the SAME
 * generateSalesRepCode logic used at link time.
 *
 *   npx tsx --env-file=.env scripts/rename-system-salesrep-codes.ts
 *   npx tsx --env-file=.env scripts/rename-system-salesrep-codes.ts --dry-run
 *
 * Each rename runs in its own transaction and writes a SalesRep UPDATE audit
 * row. Codes are display/lookup identifiers (customers reference salesRepId,
 * not code), so renaming is safe. Re-running is idempotent — once no codes
 * start with "REP-", there's nothing to do.
 */
import { AuditAction } from '../src/generated/tenant';
import { db } from '../src/lib/db';
import { audit } from '../src/lib/audit/audit';
import { generateSalesRepCode } from '../src/server/services/salesReps';

async function main() {
  const dryRun = process.argv.includes('--dry-run');
  const reps = await db.salesRep.findMany({
    where: { code: { startsWith: 'REP-' }, deletedAt: null },
    orderBy: { code: 'asc' },
  });

  if (reps.length === 0) {
    console.log('No REP- prefixed sales reps found. Nothing to do.');
    return;
  }

  console.log(
    `Found ${reps.length} sales rep(s) to rename${dryRun ? ' (dry run — no writes)' : ''}:`,
  );

  for (const rep of reps) {
    if (dryRun) {
      const preview = await db.$transaction((tx) =>
        generateSalesRepCode(tx, rep.name, rep.email),
      );
      console.log(`  ${rep.code} -> ${preview}  (${rep.name})`);
      continue;
    }

    await db.$transaction(async (tx) => {
      const newCode = await generateSalesRepCode(tx, rep.name, rep.email);
      await tx.salesRep.update({
        where: { id: rep.id },
        data: { code: newCode },
      });
      await audit(tx, {
        action: AuditAction.UPDATE,
        entityType: 'SalesRep',
        entityId: rep.id,
        before: { code: rep.code },
        after: { code: newCode },
        ctx: { userId: null, reason: 'one-time code format normalization' },
      });
      console.log(`  ${rep.code} -> ${newCode}  (${rep.name})`);
    });
  }

  console.log('Done.');
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
